steps:
      
  - label: "Running snyk node container"
    plugins:
      - aws-ssm#v1.0.0:
          parameters:
            SNYK_TOKEN: snyk_code 
      - docker#v5.10.0:
          image: "snyk/snyk:node"
          always-pull: true
          environment: $SNYK_TOKEN
    agents:
      queue: "ec2_queue"
